services:
  traefik:
    image: traefik:v3.4
    command:
      - --api.insecure=true
      - --providers.docker
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - web

  waf:
    build:
      context: .
      dockerfile: Dockerfile.waf
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.waf.rule=Host(`localhost`)"
      - "traefik.http.services.waf.loadbalancer.server.port=80"

  nextjs_app:
    image: lyhou123/next
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    external: true
